# Data Analysis And Visualization
GROUP MEMBERS: Kamogelo Macena; Kabelo Maphalala; Kyle Bee; Kabelo Sethunya; Thabang Mothoa Raymond
### GDP Growth vs Employment by Economic Sector Analysis

This notebook explores the relationship between GDP growth and employment across economic sectors, using two World Bank datasets:

- **GDP Growth**: https://data360.worldbank.org/en/indicator/WB_WDI_NY_GDP_MKTP_KD_ZG
- **Employment**: https://data360.worldbank.org/en/indicator/WB_ASPD_EMPLOYMENT

**Workflow:** load the raw data → explore and clean each dataset → align countries and years → merge into a single analysis-ready table.

## 1. Import Libraries and Load Data

Load `pandas`, `numpy`, and `matplotlib`, then read in the raw GDP and Employment CSV files.

> **Note:** the file paths below are local to the original author's machine (`C:\Users\Admin\Downloads\...`). Update these paths to point to wherever the CSVs live on your system before running.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

gdp = pd.read_csv("../../data/raw/WB_WDI_NY_GDP_MKTP_KD_ZG.csv")
employment = pd.read_csv("../../data/raw/WB_ASPD_EMPLOYMENT.csv")

## 2. Initial Data Exploration

Get a first look at the shape, structure, and contents of both datasets.

### 2.1 Dataset Dimensions
Check the number of rows and columns in each dataset.

In [2]:
print("GDP Shape:", gdp.shape)
print("Employment Shape:", employment.shape)

GDP Shape: (14321, 41)
Employment Shape: (40040, 38)

### 2.2 Column Names
List the columns available in each dataset to understand what fields we have to work with.

In [3]:
print(gdp.columns)

print(employment.columns)

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR',
       'SEX', 'AGE', 'URBANISATION', 'UNIT_MEASURE', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_3', 'TIME_PERIOD', 'OBS_VALUE',
       'AGG_METHOD', 'UNIT_TYPE', 'DECIMALS', 'DATABASE_ID', 'TIME_FORMAT',
       'UNIT_MULT', 'OBS_STATUS', 'OBS_CONF', 'FREQ_LABEL', 'REF_AREA_LABEL',
       'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', 'URBANISATION_LABEL',
       'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1_LABEL',
       'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3_LABEL', 'AGG_METHOD_LABEL',
       'UNIT_TYPE_LABEL', 'DECIMALS_LABEL', 'DATABASE_ID_LABEL',
       'TIME_FORMAT_LABEL', 'UNIT_MULT_LABEL', 'OBS_STATUS_LABEL',
       'OBS_CONF_LABEL'],
      dtype='object')
Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'FREQ_LABEL', 'REF_AREA',
       'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL', 'SEX', 'SEX_LABEL',
       'AGE', 'AGE_LABEL', 'URBANISATION', 'URBANISATION_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL', 'TIME_PERIOD',
       'OBS_VALUE', 'DATABASE_ID', 'DATABASE_ID_LABEL', 'UNIT_MULT',
       'UNIT_MULT_LABEL', 'UNIT_TYPE', 'UNIT_TYPE_LABEL', 'TIME_FORMAT',
       'TIME_FORMAT_LABEL', 'COMMENT_OBS', 'OBS_STATUS', 'OBS_STATUS_LABEL',
       'OBS_CONF', 'OBS_CONF_LABEL'],
      dtype='object')

First five rows

### 2.3 Preview the First Few Rows
Look at sample records to understand the data format and values.

In [4]:
print(gdp.head())

print(employment.head())

       STRUCTURE                STRUCTURE_ID ACTION FREQ REF_AREA  \
0  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A      ZMB
1  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A      ZWE
2  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A      AFE
3  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A      AFW
4  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A      ARB

                  INDICATOR SEX AGE URBANISATION UNIT_MEASURE  ...  \
0  WB_WDI_NY_GDP_MKTP_KD_ZG  _T  _T           _T         PC_A  ...
1  WB_WDI_NY_GDP_MKTP_KD_ZG  _T  _T           _T         PC_A  ...
2  WB_WDI_NY_GDP_MKTP_KD_ZG  _T  _T           _T         PC_A  ...
3  WB_WDI_NY_GDP_MKTP_KD_ZG  _T  _T           _T         PC_A  ...
4  WB_WDI_NY_GDP_MKTP_KD_ZG  _T  _T           _T         PC_A  ...

  COMP_BREAKDOWN_2_LABEL COMP_BREAKDOWN_3_LABEL AGG_METHOD_LABEL  \
0         Not Applicable         Not Applicable   Not Applicable
1         Not Applicable         Not Applicable   Not Applicable
2         Not Applicable         Not Applicable   Not Applicable
3         Not Applicable         Not Applicable   Not Applicable
4         Not Applicable         Not Applicable   Not Applicable

   UNIT_TYPE_LABEL  DECIMALS_LABEL                   DATABASE_ID_LABEL  \
0            Ratio             Two  World Development Indicators (WDI)
1            Ratio             Two  World Development Indicators (WDI)
2            Ratio             Two  World Development Indicators (WDI)
3            Ratio             Two  World Development Indicators (WDI)
4            Ratio             Two  World Development Indicators (WDI)

  TIME_FORMAT_LABEL  UNIT_MULT_LABEL OBS_STATUS_LABEL OBS_CONF_LABEL
0            Annual            Units     Normal value         Public
1            Annual            Units     Normal value         Public
2            Annual            Units     Normal value         Public
3            Annual            Units     Normal value         Public
4            Annual            Units     Normal value         Public

[5 rows x 41 columns]
       STRUCTURE                STRUCTURE_ID ACTION FREQ FREQ_LABEL REF_AREA  \
0  datastructure  WB.DATA360:DS_DATA360(1.2)      I    A     Annual      AGO
1  datastructure  WB.DATA360:DS_DATA360(1.2)      I    A     Annual      AGO
2  datastructure  WB.DATA360:DS_DATA360(1.2)      I    A     Annual      AGO
3  datastructure  WB.DATA360:DS_DATA360(1.2)      I    A     Annual      AGO
4  datastructure  WB.DATA360:DS_DATA360(1.2)      I    A     Annual      AGO

  REF_AREA_LABEL           INDICATOR         INDICATOR_LABEL SEX  ...  \
0         Angola  WB_ASPD_EMPLOYMENT  Employment (thousands)  _T  ...
1         Angola  WB_ASPD_EMPLOYMENT  Employment (thousands)  _T  ...
2         Angola  WB_ASPD_EMPLOYMENT  Employment (thousands)  _T  ...
3         Angola  WB_ASPD_EMPLOYMENT  Employment (thousands)  _T  ...
4         Angola  WB_ASPD_EMPLOYMENT  Employment (thousands)  _T  ...

  UNIT_MULT_LABEL UNIT_TYPE       UNIT_TYPE_LABEL TIME_FORMAT  \
0       Thousands    NUMBER  Number (real number)         602
1       Thousands    NUMBER  Number (real number)         602
2       Thousands    NUMBER  Number (real number)         602
3       Thousands    NUMBER  Number (real number)         602
4       Thousands    NUMBER  Number (real number)         602

  TIME_FORMAT_LABEL COMMENT_OBS OBS_STATUS OBS_STATUS_LABEL OBS_CONF  \
0              CCYY         NaN          A     Normal value       PU
1              CCYY         NaN          A     Normal value       PU
2              CCYY         NaN          A     Normal value       PU
3              CCYY         NaN          A     Normal value       PU
4              CCYY         NaN          A     Normal value       PU

  OBS_CONF_LABEL
0         Public
1         Public
2         Public
3         Public
4         Public

[5 rows x 38 columns]

### 2.4 Data Types and Non-Null Counts
Use `.info()` to check column data types and spot any obvious missing-data issues.

In [5]:
gdp.info()

employment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14321 entries, 0 to 14320
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               14321 non-null  object
 1   STRUCTURE_ID            14321 non-null  object
 2   ACTION                  14321 non-null  object
 3   FREQ                    14321 non-null  object
 4   REF_AREA                14321 non-null  object
 5   INDICATOR               14321 non-null  object
 6   SEX                     14321 non-null  object
 7   AGE                     14321 non-null  object
 8   URBANISATION            14321 non-null  object
 9   UNIT_MEASURE            14321 non-null  object
 10  COMP_BREAKDOWN_1        14321 non-null  object
 11  COMP_BREAKDOWN_2        14321 non-null  object
 12  COMP_BREAKDOWN_3        14321 non-null  object
 13  TIME_PERIOD             14321 non-null  int64
 14  OBS_VALUE               14321 non-null  float64
 15  AGG_METHOD              14321 non-null  object
 16  UNIT_TYPE               14321 non-null  object
 17  DECIMALS                14321 non-null  int64
 18  DATABASE_ID             14321 non-null  object
 19  TIME_FORMAT             14321 non-null  object
 20  UNIT_MULT               14321 non-null  int64
 21  OBS_STATUS              14321 non-null  object
 22  OBS_CONF                14321 non-null  object
 23  FREQ_LABEL              14321 non-null  object
 24  REF_AREA_LABEL          14321 non-null  object
 25  INDICATOR_LABEL         14321 non-null  object
 26  SEX_LABEL               14321 non-null  object
 27  AGE_LABEL               14321 non-null  object
 28  URBANISATION_LABEL      14321 non-null  object
 29  UNIT_MEASURE_LABEL      14321 non-null  object
 30  COMP_BREAKDOWN_1_LABEL  14321 non-null  object
 31  COMP_BREAKDOWN_2_LABEL  14321 non-null  object
 32  COMP_BREAKDOWN_3_LABEL  14321 non-null  object
 33  AGG_METHOD_LABEL        14321 non-null  object
 34  UNIT_TYPE_LABEL         14321 non-null  object
 35  DECIMALS_LABEL          14321 non-null  object
 36  DATABASE_ID_LABEL       14321 non-null  object
 37  TIME_FORMAT_LABEL       14321 non-null  object
 38  UNIT_MULT_LABEL         14321 non-null  object
 39  OBS_STATUS_LABEL        14321 non-null  object
 40  OBS_CONF_LABEL          14321 non-null  object
dtypes: float64(1), int64(3), object(37)
memory usage: 4.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40040 entries, 0 to 40039
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               40040 non-null  object
 1   STRUCTURE_ID            40040 non-null  object
 2   ACTION                  40040 non-null  object
 3   FREQ                    40040 non-null  object
 4   FREQ_LABEL              40040 non-null  object
 5   REF_AREA                40040 non-null  object
 6   REF_AREA_LABEL          40040 non-null  object
 7   INDICATOR               40040 non-null  object
 8   INDICATOR_LABEL         40040 non-null  object
 9   SEX                     40040 non-null  object
 10  SEX_LABEL               40040 non-null  object
 11  AGE                     40040 non-null  object
 12  AGE_LABEL               40040 non-null  object
 13  URBANISATION            40040 non-null  object
 14  URBANISATION_LABEL      40040 non-null  object
 15  UNIT_MEASURE            40040 non-null  object
 16  UNIT_MEASURE_LABEL      40040 non-null  object
 17  COMP_BREAKDOWN_1        40040 non-null  object
 18  COMP_BREAKDOWN_1_LABEL  40040 non-null  object
 19  COMP_BREAKDOWN_2        40040 non-null  object
 20  COMP_BREAKDOWN_2_LABEL  40040 non-null  object
 21  COMP_BREAKDOWN_3        40040 non-null  object
 22  COMP_BREAKDOWN_3_LABEL  40040 non-null  object
 23  TIME_PERIOD             40040 non-null  int64
 24  OBS_VALUE               39959 non-null  float64
 25  DATABASE_ID             40040 non-null  object
 26  DATABASE_ID_LABEL       40040 non-null  object
 27  UNIT_MULT               40040 non-null  int64
 28  UNIT_MULT_LABEL         40040 non-null  object
 29  UNIT_TYPE               40040 non-null  object
 30  UNIT_TYPE_LABEL         40040 non-null  object
 31  TIME_FORMAT             40040 non-null  int64
 32  TIME_FORMAT_LABEL       40040 non-null  object
 33  COMMENT_OBS             0 non-null      float64
 34  OBS_STATUS              40040 non-null  object
 35  OBS_STATUS_LABEL        40040 non-null  object
 36  OBS_CONF                40040 non-null  object
 37  OBS_CONF_LABEL          40040 non-null  object
dtypes: float64(2), int64(3), object(33)
memory usage: 11.6+ MB

## 3. Data Quality Checks

Identify missing values, duplicate rows, and clean up rows with no observation value.

### 3.1 Missing Values by Column
Count nulls per column in each dataset.

In [6]:
print(gdp.isnull().sum())

print(employment.isnull().sum())

STRUCTURE                 0
STRUCTURE_ID              0
ACTION                    0
FREQ                      0
REF_AREA                  0
INDICATOR                 0
SEX                       0
AGE                       0
URBANISATION              0
UNIT_MEASURE              0
COMP_BREAKDOWN_1          0
COMP_BREAKDOWN_2          0
COMP_BREAKDOWN_3          0
TIME_PERIOD               0
OBS_VALUE                 0
AGG_METHOD                0
UNIT_TYPE                 0
DECIMALS                  0
DATABASE_ID               0
TIME_FORMAT               0
UNIT_MULT                 0
OBS_STATUS                0
OBS_CONF                  0
FREQ_LABEL                0
REF_AREA_LABEL            0
INDICATOR_LABEL           0
SEX_LABEL                 0
AGE_LABEL                 0
URBANISATION_LABEL        0
UNIT_MEASURE_LABEL        0
COMP_BREAKDOWN_1_LABEL    0
COMP_BREAKDOWN_2_LABEL    0
COMP_BREAKDOWN_3_LABEL    0
AGG_METHOD_LABEL          0
UNIT_TYPE_LABEL           0
DECIMALS_LABEL            0
DATABASE_ID_LABEL         0
TIME_FORMAT_LABEL         0
UNIT_MULT_LABEL           0
OBS_STATUS_LABEL          0
OBS_CONF_LABEL            0
dtype: int64
STRUCTURE                     0
STRUCTURE_ID                  0
ACTION                        0
FREQ                          0
FREQ_LABEL                    0
REF_AREA                      0
REF_AREA_LABEL                0
INDICATOR                     0
INDICATOR_LABEL               0
SEX                           0
SEX_LABEL                     0
AGE                           0
AGE_LABEL                     0
URBANISATION                  0
URBANISATION_LABEL            0
UNIT_MEASURE                  0
UNIT_MEASURE_LABEL            0
COMP_BREAKDOWN_1              0
COMP_BREAKDOWN_1_LABEL        0
COMP_BREAKDOWN_2              0
COMP_BREAKDOWN_2_LABEL        0
COMP_BREAKDOWN_3              0
COMP_BREAKDOWN_3_LABEL        0
TIME_PERIOD                   0
OBS_VALUE                    81
DATABASE_ID                   0
DATABASE_ID_LABEL             0
UNIT_MULT                     0
UNIT_MULT_LABEL               0
UNIT_TYPE                     0
UNIT_TYPE_LABEL               0
TIME_FORMAT                   0
TIME_FORMAT_LABEL             0
COMMENT_OBS               40040
OBS_STATUS                    0
OBS_STATUS_LABEL              0
OBS_CONF                      0
OBS_CONF_LABEL                0
dtype: int64

### 3.2 Duplicate Rows
Check whether either dataset contains fully duplicated rows.

In [7]:
print("GDP duplicates:", gdp.duplicated().sum())

print("Employment duplicates:", employment.duplicated().sum())

GDP duplicates: 0
Employment duplicates: 0

### 3.3 Drop Rows with Missing Observation Values
`OBS_VALUE` is the core metric column (GDP growth % or employment count). Rows without it can't be used, so they're dropped.

In [8]:
gdp = gdp.dropna(subset=['OBS_VALUE'])

employment = employment.dropna(subset=['OBS_VALUE'])

### 3.4 Check Key Categorical Filters
Inspect the `AGE_LABEL` and `URBANISATION_LABEL` columns to see whether the data is already filtered to a single demographic slice (e.g. "Total" age group, "Total" urbanisation) or contains multiple breakdowns that need to be filtered later.

In [9]:
print(gdp['AGE_LABEL'].value_counts())
print(gdp['URBANISATION_LABEL'].value_counts())

print(employment['AGE_LABEL'].value_counts())
print(employment['URBANISATION_LABEL'].value_counts())

AGE_LABEL
All age ranges or no breakdown by age    14321
Name: count, dtype: int64
URBANISATION_LABEL
Total    14321
Name: count, dtype: int64
AGE_LABEL
All age ranges or no breakdown by age    39959
Name: count, dtype: int64
URBANISATION_LABEL
Total    39959
Name: count, dtype: int64

## 4. Detailed Column Profiling

For every column, print its data type, missing-value count, number of unique values, and a sample of unique values. This gives a fast, complete picture of each dataset's structure before deciding how to clean and merge them.

### 4.1 GDP Dataset Column Profile

In [10]:
for col in gdp.columns:
    print("="*60)
    print("Column:", col)
    print("Data Type:", gdp[col].dtype)
    print("Missing:", gdp[col].isnull().sum())
    print("Unique Values:", gdp[col].nunique())
    print(gdp[col].unique()[:10])

============================================================
Column: STRUCTURE
Data Type: object
Missing: 0
Unique Values: 1
['datastructure']
============================================================
Column: STRUCTURE_ID
Data Type: object
Missing: 0
Unique Values: 1
['WB.DATA360:DS_DATA360(1.3)']
============================================================
Column: ACTION
Data Type: object
Missing: 0
Unique Values: 1
['I']
============================================================
Column: FREQ
Data Type: object
Missing: 0
Unique Values: 1
['A']
============================================================
Column: REF_AREA
Data Type: object
Missing: 0
Unique Values: 261
['ZMB' 'ZWE' 'AFE' 'AFW' 'ARB' 'CSS' 'CEB' 'EAR' 'EAS' 'EAP']
============================================================
Column: INDICATOR
Data Type: object
Missing: 0
Unique Values: 1
['WB_WDI_NY_GDP_MKTP_KD_ZG']
============================================================
Column: SEX
Data Type: object
Missing: 0
Unique Values: 1
['_T']
============================================================
Column: AGE
Data Type: object
Missing: 0
Unique Values: 1
['_T']
============================================================
Column: URBANISATION
Data Type: object
Missing: 0
Unique Values: 1
['_T']
============================================================
Column: UNIT_MEASURE
Data Type: object
Missing: 0
Unique Values: 1
['PC_A']
============================================================
Column: COMP_BREAKDOWN_1
Data Type: object
Missing: 0
Unique Values: 1
['_Z']
============================================================
Column: COMP_BREAKDOWN_2
Data Type: object
Missing: 0
Unique Values: 1
['_Z']
============================================================
Column: COMP_BREAKDOWN_3
Data Type: object
Missing: 0
Unique Values: 1
['_Z']
============================================================
Column: TIME_PERIOD
Data Type: int64
Missing: 0
Unique Values: 65
[2015 2016 2005 2006 2017 2018 2014 2019 2011 2012]
============================================================
Column: OBS_VALUE
Data Type: float64
Missing: 0
Unique Values: 14194
[ 2.92037511  1.77985356  2.29250058  0.17617172  3.57245634 -3.08739815
  2.80724942  4.14710614  4.63114688  6.50852875]
============================================================
Column: AGG_METHOD
Data Type: object
Missing: 0
Unique Values: 1
['_Z']
============================================================
Column: UNIT_TYPE
Data Type: object
Missing: 0
Unique Values: 1
['RATIO']
============================================================
Column: DECIMALS
Data Type: int64
Missing: 0
Unique Values: 1
[2]
============================================================
Column: DATABASE_ID
Data Type: object
Missing: 0
Unique Values: 1
['WB_WDI']
============================================================
Column: TIME_FORMAT
Data Type: object
Missing: 0
Unique Values: 1
['P1Y']
============================================================
Column: UNIT_MULT
Data Type: int64
Missing: 0
Unique Values: 1
[0]
============================================================
Column: OBS_STATUS
Data Type: object
Missing: 0
Unique Values: 1
['A']
============================================================
Column: OBS_CONF
Data Type: object
Missing: 0
Unique Values: 1
['PU']
============================================================
Column: FREQ_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Annual']
============================================================
Column: REF_AREA_LABEL
Data Type: object
Missing: 0
Unique Values: 261
['Zambia' 'Zimbabwe' 'Africa Eastern and Southern'
 'Africa Western and Central' 'Arab World' 'Caribbean small states'
 'Central Europe and the Baltics' 'Early-demographic dividend'
 'East Asia & Pacific' 'East Asia & Pacific (excluding high income)']
============================================================
Column: INDICATOR_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['GDP growth (annual %)']
============================================================
Column: SEX_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Total']
============================================================
Column: AGE_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['All age ranges or no breakdown by age']
============================================================
Column: URBANISATION_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Total']
============================================================
Column: UNIT_MEASURE_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Percentage change per annum']
============================================================
Column: COMP_BREAKDOWN_1_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Not Applicable']
============================================================
Column: COMP_BREAKDOWN_2_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Not Applicable']
============================================================
Column: COMP_BREAKDOWN_3_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Not Applicable']
============================================================
Column: AGG_METHOD_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Not Applicable']
============================================================
Column: UNIT_TYPE_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Ratio']
============================================================
Column: DECIMALS_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Two']
============================================================
Column: DATABASE_ID_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['World Development Indicators (WDI)']
============================================================
Column: TIME_FORMAT_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Annual']
============================================================
Column: UNIT_MULT_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Units']
============================================================
Column: OBS_STATUS_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Normal value']
============================================================
Column: OBS_CONF_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Public']

### 4.1 Employment Dataset Column Profile

In [11]:
for col in employment.columns:
    print("="*60)
    print("Column:", col)
    print("Data Type:", employment[col].dtype)
    print("Missing:", employment[col].isnull().sum())
    print("Unique Values:", employment[col].nunique())
    print(employment[col].unique()[:10])

============================================================
Column: STRUCTURE
Data Type: object
Missing: 0
Unique Values: 1
['datastructure']
============================================================
Column: STRUCTURE_ID
Data Type: object
Missing: 0
Unique Values: 1
['WB.DATA360:DS_DATA360(1.2)']
============================================================
Column: ACTION
Data Type: object
Missing: 0
Unique Values: 1
['I']
============================================================
Column: FREQ
Data Type: object
Missing: 0
Unique Values: 1
['A']
============================================================
Column: FREQ_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Annual']
============================================================
Column: REF_AREA
Data Type: object
Missing: 0
Unique Values: 103
['AGO' 'ARG' 'AUS' 'AUT' 'AZE' 'BEL' 'BFA' 'BGD' 'BGR' 'BLZ']
============================================================
Column: REF_AREA_LABEL
Data Type: object
Missing: 0
Unique Values: 103
['Angola' 'Argentina' 'Australia' 'Austria' 'Azerbaijan' 'Belgium'
 'Burkina Faso' 'Bangladesh' 'Bulgaria' 'Belize']
============================================================
Column: INDICATOR
Data Type: object
Missing: 0
Unique Values: 1
['WB_ASPD_EMPLOYMENT']
============================================================
Column: INDICATOR_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Employment (thousands)']
============================================================
Column: SEX
Data Type: object
Missing: 0
Unique Values: 1
['_T']
============================================================
Column: SEX_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Total']
============================================================
Column: AGE
Data Type: object
Missing: 0
Unique Values: 1
['_T']
============================================================
Column: AGE_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['All age ranges or no breakdown by age']
============================================================
Column: URBANISATION
Data Type: object
Missing: 0
Unique Values: 1
['_T']
============================================================
Column: URBANISATION_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Total']
============================================================
Column: UNIT_MEASURE
Data Type: object
Missing: 0
Unique Values: 1
['PS']
============================================================
Column: UNIT_MEASURE_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Persons']
============================================================
Column: COMP_BREAKDOWN_1
Data Type: object
Missing: 0
Unique Values: 10
['WB_ASPD_TOTAL' 'WB_ASPD_1' 'WB_ASPD_2' 'WB_ASPD_3' 'WB_ASPD_4'
 'WB_ASPD_5' 'WB_ASPD_6' 'WB_ASPD_7' 'WB_ASPD_8' 'WB_ASPD_9']
============================================================
Column: COMP_BREAKDOWN_1_LABEL
Data Type: object
Missing: 0
Unique Values: 10
['Sector: Total' 'Sector: Agriculture' 'Sector: Mining'
 'Sector: Manufacturing' 'Sector: Utilities' 'Sector: Construction'
 'Sector: Trade services' 'Sector: Transport services'
 'Sector: Finance and business services' 'Sector: Other services']
============================================================
Column: COMP_BREAKDOWN_2
Data Type: object
Missing: 0
Unique Values: 1
['_Z']
============================================================
Column: COMP_BREAKDOWN_2_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Not Applicable']
============================================================
Column: COMP_BREAKDOWN_3
Data Type: object
Missing: 0
Unique Values: 1
['_Z']
============================================================
Column: COMP_BREAKDOWN_3_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Not Applicable']
============================================================
Column: TIME_PERIOD
Data Type: int64
Missing: 0
Unique Values: 68
[2002 2003 2004 2005 2006 2007 2008 2009 2010 2011]
============================================================
Column: OBS_VALUE
Data Type: float64
Missing: 0
Unique Values: 39371
[5471.14013672 2022.175        60.773       168.209        17.595
  250.817      1415.09606934  210.613        45.92900085 1279.9329834 ]
============================================================
Column: DATABASE_ID
Data Type: object
Missing: 0
Unique Values: 1
['WB_ASPD']
============================================================
Column: DATABASE_ID_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Global Productivity: A Cross-country Database of Productivity']
============================================================
Column: UNIT_MULT
Data Type: int64
Missing: 0
Unique Values: 1
[3]
============================================================
Column: UNIT_MULT_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Thousands']
============================================================
Column: UNIT_TYPE
Data Type: object
Missing: 0
Unique Values: 1
['NUMBER']
============================================================
Column: UNIT_TYPE_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Number (real number)']
============================================================
Column: TIME_FORMAT
Data Type: int64
Missing: 0
Unique Values: 1
[602]
============================================================
Column: TIME_FORMAT_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['CCYY']
============================================================
Column: COMMENT_OBS
Data Type: float64
Missing: 39959
Unique Values: 0
[nan]
============================================================
Column: OBS_STATUS
Data Type: object
Missing: 0
Unique Values: 1
['A']
============================================================
Column: OBS_STATUS_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Normal value']
============================================================
Column: OBS_CONF
Data Type: object
Missing: 0
Unique Values: 1
['PU']
============================================================
Column: OBS_CONF_LABEL
Data Type: object
Missing: 0
Unique Values: 1
['Public']

## 5. Country Coverage Comparison

Before merging, check how much overlap exists between the countries/regions reported in each dataset.

### 5.1 Compare Country Sets
Count countries in each dataset and how many are common to both.

In [12]:
gdp_countries = set(gdp['REF_AREA_LABEL'])
employment_countries = set(employment['REF_AREA_LABEL'])

common = gdp_countries.intersection(employment_countries)

print("GDP countries:", len(gdp_countries))
print("Employment countries:", len(employment_countries))
print("Common countries:", len(common))

GDP countries: 261
Employment countries: 103
Common countries: 100

### 5.2 Countries Present in GDP but Missing from Employment
List the specific countries/regions that will be lost if we restrict the analysis to countries common to both datasets.

In [13]:
missing = sorted(gdp_countries - employment_countries)

print("Countries/regions in GDP but not Employment:")
print(missing)

Countries/regions in GDP but not Employment:
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'American Samoa', 'Andorra', 'Antigua and Barbuda', 'Arab World', 'Armenia', 'Aruba', 'Bahamas, The', 'Bahrain', 'Barbados', 'Belarus', 'Benin', 'Bermuda', 'Bhutan', 'Bosnia and Herzegovina', 'Brunei Darussalam', 'Burundi', 'Cabo Verde', 'Cambodia', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Cuba', 'Curaçao', 'Côte d’Ivoire', 'Djibouti', 'Dominica', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD)', 'East Asia & Pacific (excluding high income)', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'French Polynesia', 'Gabon', 'Gambia, The', 'Greenland', 'Grenada', 'Guam', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iraq', 'Isle of Man', 'Israel', 'Kazakhstan', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (IDA & IBRD)', 'Latin America & Caribbean (excluding high income)', 'Least developed countries: UN classification', 'Lebanon', 'Liberia', 'Libya', 'Liechtenstein', 'Low & middle income', 'Low income', 'Lower middle income', 'Macao SAR, China', 'Madagascar', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Micronesia, Fed. Sts.', 'Middle East, North Africa, Afghanistan & Pakistan', 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)', 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Myanmar', 'Nauru', 'New Caledonia', 'Nicaragua', 'Niger', 'North America', 'North Macedonia', 'Northern Mariana Islands', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Palau', 'Panama', 'Papua New Guinea', 'Peru', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico', 'Samoa', 'San Marino', 'Saudi Arabia', 'Seychelles', 'Sint Maarten (Dutch part)', 'Small states', 'Solomon Islands', 'Somalia, Federal Republic of', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'St. Kitts and Nevis', 'St. Martin (French part)', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Syrian Arab Republic', 'São Tomé and Príncipe', 'Tajikistan', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Türkiye', 'Ukraine', 'United Arab Emirates', 'Upper middle income', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zimbabwe']

## 6. GDP Dataset — Detailed Exploration

A closer look at the GDP dataset's coverage and categorical fields.

In [14]:
print("GDP Year Range:")
print(gdp['TIME_PERIOD'].min(), "-", gdp['TIME_PERIOD'].max())

print("Number of unique years:")
print(gdp['TIME_PERIOD'].nunique())

print("\nFirst 10 years:")
print(sorted(gdp['TIME_PERIOD'].unique())[:10])

print("\nLast 10 years:")
print(sorted(gdp['TIME_PERIOD'].unique())[-10:])

GDP Year Range:
1961 - 2025
Number of unique years:
65

First 10 years:
[np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970)]

Last 10 years:
[np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

In [15]:
print("Number of countries/regions:")
print(gdp['REF_AREA_LABEL'].nunique())

Number of countries/regions:
261

In [16]:
print(gdp['INDICATOR_LABEL'].value_counts())

INDICATOR_LABEL
GDP growth (annual %)    14321
Name: count, dtype: int64

In [17]:
print(gdp['UNIT_MEASURE_LABEL'].value_counts())

UNIT_MEASURE_LABEL
Percentage change per annum    14321
Name: count, dtype: int64

In [18]:
print(gdp['AGE_LABEL'].value_counts())

AGE_LABEL
All age ranges or no breakdown by age    14321
Name: count, dtype: int64

In [19]:
print(gdp['SEX_LABEL'].value_counts())

SEX_LABEL
Total    14321
Name: count, dtype: int64

In [20]:
print(gdp['URBANISATION_LABEL'].value_counts())

URBANISATION_LABEL
Total    14321
Name: count, dtype: int64

## 7. Employment Dataset — Detailed Exploration

Run the same style of summary for the Employment dataset in one pass: year range, country count, and value counts for indicator, gender, age, urbanisation, sector, unit, and missing values.

In [21]:
print("Employment Year Range:")
print(employment['TIME_PERIOD'].min(), "-", employment['TIME_PERIOD'].max())

print("\nNumber of countries:")
print(employment['REF_AREA_LABEL'].nunique())

print("\nIndicator")
print(employment['INDICATOR_LABEL'].value_counts())

print("\nGender")
print(employment['SEX_LABEL'].value_counts())

print("\nAge")
print(employment['AGE_LABEL'].value_counts())

print("\nUrbanisation")
print(employment['URBANISATION_LABEL'].value_counts())

print("\nSector")
print(employment['COMP_BREAKDOWN_1_LABEL'].value_counts())

print("\nUnit")
print(employment['UNIT_MEASURE_LABEL'].value_counts())

print("\nMissing values")
print(employment.isnull().sum())

Employment Year Range:
1950 - 2017

Number of countries:
103

Indicator
INDICATOR_LABEL
Employment (thousands)    39959
Name: count, dtype: int64

Gender
SEX_LABEL
Total    39959
Name: count, dtype: int64

Age
AGE_LABEL
All age ranges or no breakdown by age    39959
Name: count, dtype: int64

Urbanisation
URBANISATION_LABEL
Total    39959
Name: count, dtype: int64

Sector
COMP_BREAKDOWN_1_LABEL
Sector: Other services                   4004
Sector: Total                            3995
Sector: Agriculture                      3995
Sector: Mining                           3995
Sector: Utilities                        3995
Sector: Manufacturing                    3995
Sector: Construction                     3995
Sector: Trade services                   3995
Sector: Transport services               3995
Sector: Finance and business services    3995
Name: count, dtype: int64

Unit
UNIT_MEASURE_LABEL
Persons    39959
Name: count, dtype: int64

Missing values
STRUCTURE                     0
STRUCTURE_ID                  0
ACTION                        0
FREQ                          0
FREQ_LABEL                    0
REF_AREA                      0
REF_AREA_LABEL                0
INDICATOR                     0
INDICATOR_LABEL               0
SEX                           0
SEX_LABEL                     0
AGE                           0
AGE_LABEL                     0
URBANISATION                  0
URBANISATION_LABEL            0
UNIT_MEASURE                  0
UNIT_MEASURE_LABEL            0
COMP_BREAKDOWN_1              0
COMP_BREAKDOWN_1_LABEL        0
COMP_BREAKDOWN_2              0
COMP_BREAKDOWN_2_LABEL        0
COMP_BREAKDOWN_3              0
COMP_BREAKDOWN_3_LABEL        0
TIME_PERIOD                   0
OBS_VALUE                     0
DATABASE_ID                   0
DATABASE_ID_LABEL             0
UNIT_MULT                     0
UNIT_MULT_LABEL               0
UNIT_TYPE                     0
UNIT_TYPE_LABEL               0
TIME_FORMAT                   0
TIME_FORMAT_LABEL             0
COMMENT_OBS               39959
OBS_STATUS                    0
OBS_STATUS_LABEL              0
OBS_CONF                      0
OBS_CONF_LABEL                0
dtype: int64

## 8. Dataset Size Comparison Summary

In [22]:
print("GDP observations:", len(gdp))
print("GDP countries:", gdp['REF_AREA_LABEL'].nunique())
print("GDP years:", gdp['TIME_PERIOD'].nunique())

print("\nEmployment observations:", len(employment))
print("Employment countries:", employment['REF_AREA_LABEL'].nunique())
print("Employment years:", employment['TIME_PERIOD'].nunique())

GDP observations: 14321
GDP countries: 261
GDP years: 65

Employment observations: 39959
Employment countries: 103
Employment years: 68

## 10. Investigate Sector Count Anomalies

Each country-year in the Employment dataset should report the same fixed number of sectors (10). Here we check whether that's actually true, and investigate the exceptions.

In [23]:
employment.groupby(
    ['REF_AREA_LABEL', 'TIME_PERIOD']
)['COMP_BREAKDOWN_1_LABEL'].nunique().value_counts()

COMP_BREAKDOWN_1_LABEL
10    3995
1        9
Name: count, dtype: int64

In [24]:
problem_cases = employment.groupby(
    ['REF_AREA_LABEL', 'TIME_PERIOD']
)['COMP_BREAKDOWN_1_LABEL'].nunique()

problem_cases = problem_cases[problem_cases == 1]

print(problem_cases)

REF_AREA_LABEL  TIME_PERIOD
Botswana        1964           1
                1965           1
                1966           1
                1967           1
Namibia         1960           1
                1961           1
                1962           1
                1963           1
                1964           1
Name: COMP_BREAKDOWN_1_LABEL, dtype: int64

In [25]:
employment[
    (employment['REF_AREA_LABEL'].isin(problem_cases.index.get_level_values(0))) &
    (employment['TIME_PERIOD'].isin(problem_cases.index.get_level_values(1)))
].sort_values(['REF_AREA_LABEL', 'TIME_PERIOD'])

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,COMMENT_OBS,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
3959,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,BWA,Botswana,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
3969,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,BWA,Botswana,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
3979,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,BWA,Botswana,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
3989,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,BWA,Botswana,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27129,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27139,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27149,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27159,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27169,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27170,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27171,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27172,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27173,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27174,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27175,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27176,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27177,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27178,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27179,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27180,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27181,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27182,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27183,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27184,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27185,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27186,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27187,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27188,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27189,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27190,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27191,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27192,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27193,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27194,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27195,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27196,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27197,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27198,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public
27199,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,NAM,Namibia,WB_ASPD_EMPLOYMENT,Employment (thousands),_T,...,Thousands,NUMBER,Number (real number),602,CCYY,NaN,A,Normal value,PU,Public

In [26]:
employment.loc[
    employment.set_index(['REF_AREA_LABEL', 'TIME_PERIOD']).index.isin(problem_cases.index),
    ['REF_AREA_LABEL', 'TIME_PERIOD', 'COMP_BREAKDOWN_1_LABEL', 'OBS_VALUE']
].sort_values(['REF_AREA_LABEL', 'TIME_PERIOD'])

      REF_AREA_LABEL  TIME_PERIOD  COMP_BREAKDOWN_1_LABEL  OBS_VALUE
3959        Botswana         1964  Sector: Other services  11.343030
3969        Botswana         1965  Sector: Other services  13.797582
3979        Botswana         1966  Sector: Other services  16.122666
3989        Botswana         1967  Sector: Other services  18.631292
27129        Namibia         1960  Sector: Other services  33.764664
27139        Namibia         1961  Sector: Other services  35.509396
27149        Namibia         1962  Sector: Other services  37.344616
27159        Namibia         1963  Sector: Other services  39.275033
27169        Namibia         1964  Sector: Other services  41.305610

## 11. Fix: Keep Only Country-Years with the Full Set of 10 Sectors

To keep the dataset consistent, drop any country-year that doesn't report all 10 sectors, then confirm the fix worked.

In [27]:
sector_count = employment.groupby(
    ['REF_AREA_LABEL', 'TIME_PERIOD']
)['COMP_BREAKDOWN_1_LABEL'].transform('nunique')

employment = employment[sector_count == 10]

In [28]:
employment.groupby(
    ['REF_AREA_LABEL', 'TIME_PERIOD']
)['COMP_BREAKDOWN_1_LABEL'].nunique().value_counts()

COMP_BREAKDOWN_1_LABEL
10    3995
Name: count, dtype: int64

## 12. Align Countries Between Datasets

Restrict both datasets to only the countries present in both, so the merge later doesn't produce mismatched or one-sided rows.

In [29]:
common_countries = set(gdp['REF_AREA_LABEL']) & set(employment['REF_AREA_LABEL'])

print(len(common_countries))

100

In [30]:
gdp = gdp[gdp['REF_AREA_LABEL'].isin(common_countries)]
employment = employment[employment['REF_AREA_LABEL'].isin(common_countries)]

## 13. Align Time Periods

Restrict both datasets to the years they have in common.



### 13.1 Check Current Year Ranges

In [31]:
print("GDP:")
print(gdp['TIME_PERIOD'].min(), "-", gdp['TIME_PERIOD'].max())

print("Employment:")
print(employment['TIME_PERIOD'].min(), "-", employment['TIME_PERIOD'].max())

GDP:
1961 - 2025
Employment:
1950 - 2017

### 13.2 Filter to the Overlapping Year Range (1961–2017)

In [32]:
gdp = gdp[
    (gdp['TIME_PERIOD'] >= 1961) &
    (gdp['TIME_PERIOD'] <= 2017)
]

employment = employment[
    (employment['TIME_PERIOD'] >= 1961) &
    (employment['TIME_PERIOD'] <= 2017)
]

### 13.3 Verify the Filtered Ranges and Shapes

In [33]:
print("GDP")
print(gdp['TIME_PERIOD'].min(), "-", gdp['TIME_PERIOD'].max())
print(gdp.shape)

print("\nEmployment")
print(employment['TIME_PERIOD'].min(), "-", employment['TIME_PERIOD'].max())
print(employment.shape)

GDP
1961 - 2017
(5069, 41)

Employment
1961 - 2017
(38110, 38)

## 14. Merge GDP and Employment Data

Join the two cleaned datasets on `REF_AREA_LABEL` (country) and `TIME_PERIOD` (year).

### 14.1 Perform the Merge

In [34]:
merged = pd.merge(
    gdp,
    employment,
    on=['REF_AREA_LABEL', 'TIME_PERIOD'],
    how='inner'
)

print(merged.shape)

(37700, 77)

### 14.2 Check Merge Quality
Confirm the merged shape and check for any missing GDP or Employment values introduced by the join.

In [35]:
print(merged.shape)

print(merged[['REF_AREA_LABEL', 'TIME_PERIOD']].head())

print("Missing GDP values:")
print(merged['OBS_VALUE_x'].isna().sum())

print("Missing Employment values:")
print(merged['OBS_VALUE_y'].isna().sum())

(37700, 77)
  REF_AREA_LABEL  TIME_PERIOD
0         Zambia         2015
1         Zambia         2015
2         Zambia         2015
3         Zambia         2015
4         Zambia         2015
Missing GDP values:
0
Missing Employment values:
0

## 15. Clean Up Merged Dataset Columns

Rename the ambiguous `_x`/`_y` suffix columns produced by the merge into clear, descriptive names.

### 15.1 Rename Core Value Columns

In [36]:
merged = merged.rename(columns={
    'OBS_VALUE_x': 'GDP_Growth',
    'OBS_VALUE_y': 'Employment_Thousands',
    'COMP_BREAKDOWN_1_LABEL': 'Sector'
})

In [37]:
merged = merged.rename(columns={
    'COMP_BREAKDOWN_1_LABEL_y': 'Sector'
})

In [38]:
merged[['REF_AREA_LABEL',
        'TIME_PERIOD',
        'GDP_Growth',
        'Employment_Thousands',
        'Sector']].head()

,REF_AREA_LABEL,TIME_PERIOD,GDP_Growth,Employment_Thousands,Sector
0,Zambia,2015,2.920375,4532.103027,Sector: Total
1,Zambia,2015,2.920375,3089.903564,Sector: Agriculture
2,Zambia,2015,2.920375,99.403816,Sector: Mining
3,Zambia,2015,2.920375,180.855972,Sector: Manufacturing
4,Zambia,2015,2.920375,10.042576,Sector: Utilities

## 16. Final Dataset Summary

A last check of the merged, cleaned dataset before moving on to analysis and visualization.

In [39]:
print("Countries:", merged['REF_AREA_LABEL'].nunique())
print(
    merged['TIME_PERIOD'].min(),
    "-",
    merged['TIME_PERIOD'].max()
)
print(merged['Sector'].value_counts())

Countries: 100
1961 - 2017
Sector
Sector: Total                            3770
Sector: Agriculture                      3770
Sector: Mining                           3770
Sector: Manufacturing                    3770
Sector: Utilities                        3770
Sector: Construction                     3770
Sector: Trade services                   3770
Sector: Transport services               3770
Sector: Finance and business services    3770
Sector: Other services                   3770
Name: count, dtype: int64

### 16.2 Missing Values and Duplicates Check

In [40]:
print(merged[['GDP_Growth',
              'Employment_Thousands',
              'Sector']].isnull().sum())

print("Duplicates:", merged.duplicated().sum())

GDP_Growth              0
Employment_Thousands    0
Sector                  0
dtype: int64
Duplicates: 0


# FOR YOUR ATTENTION 

The data types of all variables were inspected to ensure they were appropriate for analysis. The year variable was stored as an integer, GDP growth and employment values as floating-point numbers, and categorical variables such as country and sector as text. No data type conversion was necessary.

### 17. Data Validation

After merging, we check the final dataset for missing values and duplicates to make sure the integration did not introduce problems.

In [41]:
print(merged.head())
print("\nShape:", merged.shape)

print("\nMissing values:")
print(merged[[
    "GDP_Growth",
    "Employment_Thousands",
    "Sector"
]].isnull().sum())

print("\nDuplicates:", merged.duplicated().sum())

     STRUCTURE_x              STRUCTURE_ID_x ACTION_x FREQ_x REF_AREA_x  \
0  datastructure  WB.DATA360:DS_DATA360(1.3)        I      A        ZMB
1  datastructure  WB.DATA360:DS_DATA360(1.3)        I      A        ZMB
2  datastructure  WB.DATA360:DS_DATA360(1.3)        I      A        ZMB
3  datastructure  WB.DATA360:DS_DATA360(1.3)        I      A        ZMB
4  datastructure  WB.DATA360:DS_DATA360(1.3)        I      A        ZMB

                INDICATOR_x SEX_x AGE_x URBANISATION_x UNIT_MEASURE_x  ...  \
0  WB_WDI_NY_GDP_MKTP_KD_ZG    _T    _T             _T           PC_A  ...
1  WB_WDI_NY_GDP_MKTP_KD_ZG    _T    _T             _T           PC_A  ...
2  WB_WDI_NY_GDP_MKTP_KD_ZG    _T    _T             _T           PC_A  ...
3  WB_WDI_NY_GDP_MKTP_KD_ZG    _T    _T             _T           PC_A  ...
4  WB_WDI_NY_GDP_MKTP_KD_ZG    _T    _T             _T           PC_A  ...

  UNIT_MULT_LABEL_y UNIT_TYPE_y     UNIT_TYPE_LABEL_y  TIME_FORMAT_y  \
0         Thousands      NUMBER  Number (real number)            602
1         Thousands      NUMBER  Number (real number)            602
2         Thousands      NUMBER  Number (real number)            602
3         Thousands      NUMBER  Number (real number)            602
4         Thousands      NUMBER  Number (real number)            602

   TIME_FORMAT_LABEL_y COMMENT_OBS OBS_STATUS_y  OBS_STATUS_LABEL_y  \
0                 CCYY         NaN            A        Normal value
1                 CCYY         NaN            A        Normal value
2                 CCYY         NaN            A        Normal value
3                 CCYY         NaN            A        Normal value
4                 CCYY         NaN            A        Normal value

  OBS_CONF_y OBS_CONF_LABEL_y
0         PU           Public
1         PU           Public
2         PU           Public
3         PU           Public
4         PU           Public

[5 rows x 77 columns]

Shape: (37700, 77)

Missing values:
GDP_Growth              0
Employment_Thousands    0
Sector                  0
dtype: int64

Duplicates: 0

## Final Dataset Preparation

We create the final analysis-ready dataset containing 37,700 observations and 5 columns.

In [42]:
final_data = merged[
    [
        "REF_AREA_LABEL",
        "TIME_PERIOD",
        "GDP_Growth",
        "Employment_Thousands",
        "Sector"
    ]
].copy()

print(final_data.head())
print("\nShape:", final_data.shape)

  REF_AREA_LABEL  TIME_PERIOD  GDP_Growth  Employment_Thousands  \
0         Zambia         2015    2.920375           4532.103027
1         Zambia         2015    2.920375           3089.903564
2         Zambia         2015    2.920375             99.403816
3         Zambia         2015    2.920375            180.855972
4         Zambia         2015    2.920375             10.042576

                  Sector
0          Sector: Total
1    Sector: Agriculture
2         Sector: Mining
3  Sector: Manufacturing
4      Sector: Utilities

Shape: (37700, 5)

## Clean Data Export

Finally, we save the cleaned dataset in data/clean/ so that the other group members can use the same prepared data for Section  2–16.

In [44]:
final_data.to_csv(
    "../../data/clean/GDP_Employment_Cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [45]:
cleaned_check = pd.read_csv("../../data/clean/GDP_Employment_Cleaned.csv")

print("Shape:", cleaned_check.shape)

print("\nColumns:")
print(cleaned_check.columns.tolist())

print("\nMissing values:")
print(cleaned_check.isnull().sum())

print("\nDuplicates:", cleaned_check.duplicated().sum())

print("\nFirst 5 rows:")
display(cleaned_check.head())

Shape: (37700, 5)

Columns:
['REF_AREA_LABEL', 'TIME_PERIOD', 'GDP_Growth', 'Employment_Thousands', 'Sector']

Missing values:
REF_AREA_LABEL          0
TIME_PERIOD             0
GDP_Growth              0
Employment_Thousands    0
Sector                  0
dtype: int64

Duplicates: 0

First 5 rows:

,REF_AREA_LABEL,TIME_PERIOD,GDP_Growth,Employment_Thousands,Sector
0,Zambia,2015,2.920375,4532.103027,Sector: Total
1,Zambia,2015,2.920375,3089.903564,Sector: Agriculture
2,Zambia,2015,2.920375,99.403816,Sector: Mining
3,Zambia,2015,2.920375,180.855972,Sector: Manufacturing
4,Zambia,2015,2.920375,10.042576,Sector: Utilities